targets:
  $default:
    sources:
      - swagger/**
    builders:
      swagger_dart_code_generator:
        options:
          with_base_url: true
          with_converter: true
          use_required_attribute_for_headers: true
          ignore_headers: false
          use_default_null_for_lists: false
          use_inheritance: false
          build_only_models: false
          model_postfix: ""
          use_path_for_request_names: true
          include_if_null:
            enabled: true
            value: false
          input_folder: "swagger/"
          output_folder: "lib/network/swagger/"
          enums_case_sensitive: true