name: ding
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.22.0
  country_code_picker: ^2.0.2
  pin_code_text_field: ^1.8.0
  jalali_calendar: ^1.0.4
  flutter_picker: ^2.0.2
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  logger: ^1.0.0
  swagger:
    path: ./swagger

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/eye.svg
    - assets/images/form.svg
    - assets/images/letter.svg
    - assets/images/timer.svg
    - assets/images/other.svg
    - assets/images/Shape.svg
    - assets/images/mail.svg
    - assets/images/phone.svg
    - assets/images/device.svg
    - assets/images/location.svg
    - assets/images/cloud.svg
    - assets/images/telegram.svg
    - assets/images/instagram.svg
    - assets/images/info.svg
    - assets/images/setting.svg
    - assets/images/support.svg
    - assets/images/edit.svg
    - assets/images/manage-icon.svg
    - assets/images/web.svg
    - assets/images/log-in.svg
    - assets/images/log-out.svg
    - assets/images/trash2.svg
    - assets/images/list.svg
    - assets/images/calendar.svg
    - assets/images/clock.svg
    - assets/images/name_logo.svg

  fonts:
   - family: IRANYekan
     fonts:
       - asset: assets/fonts/IRANYekanBlack.ttf
       - asset: assets/fonts/IRANYekanBold.ttf
       - asset: assets/fonts/IRANYekanExtraBlack.ttf
       - asset: assets/fonts/IRANYekanExtraBold.ttf
       - asset: assets/fonts/IRANYekanLight.ttf
       - asset: assets/fonts/IRANYekanMedium.ttf
       - asset: assets/fonts/IRANYekanRegular.ttf
       - asset: assets/fonts/IRANYekanThin.ttf